### ISSUE TITLE
Stop independent services in kube-compose defined in docker-compose.yml

### ISSUE THREAD

**Issue by maheshrayas** [jbrekelmans/kube-compose#68]
kube-compose down should be able to stop independent services.

For eg:  kube-compose down service-1

**Comment by jbrekelmans** [comment]
K8s services should only be deleted if down would stop all compose services. This is so that existing pods will not have their hostAliases invalidated by a partial down. For example, suppose we have a docker-compose file with two services a and b, and we run the following commands:
```
kube-compose up
kube-compose down a
kube-compose up a
```
If `kube-compose down a` deletes the k8s service of a, then the host aliases set on the pod for b are no longer valid (because the k8s service of a has a new IP).
