### ISSUE TITLE
Investigate if viper maps env-id to ENVID or it also allows ENV_ID

### ISSUE THREAD

**Issue by jbrekelmans** [jbrekelmans/kube-compose#80]

**Comment by lawrence501** [comment]
As you can see by following logic in Viper's [`find`](https://github.com/spf13/viper/blob/master/viper.go#L1024) function, it quite literally merges the EnvPrefix (we've set to `kubecompose`) with an underscore and then with the input to find (originally from `GetString` in our case), all made uppercase.

Because of this, whatever we pass to GetString will be the suffix of the env var it looks for. We are currently passing `envid`, which is why our env var is `ENVID`. If we want `ENV_ID` instead, we need to pass `env_id` to `viper.GetString`.
